//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CallerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VendorName" type="{http://www.drfirst.com/}AN30" minOccurs="0"/>
 *         &lt;element name="VendorPassword" type="{http://www.drfirst.com/}AN35" minOccurs="0"/>
 *         &lt;element name="Application" type="{http://www.drfirst.com/}AN100"/>
 *         &lt;element name="Version" type="{http://www.drfirst.com/}AN40"/>
 *         &lt;element name="PracticeName" type="{http://www.drfirst.com/}AN100"/>
 *         &lt;element name="Station" type="{http://www.drfirst.com/}AN100" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallerType", propOrder = {
    "vendorName",
    "vendorPassword",
    "application",
    "version",
    "practiceName",
    "station"
})
public class CallerType {

    @XmlElement(name = "VendorName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String vendorName;
    @XmlElement(name = "VendorPassword")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String vendorPassword;
    @XmlElement(name = "Application", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String application;
    @XmlElement(name = "Version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;
    @XmlElement(name = "PracticeName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String practiceName;
    @XmlElement(name = "Station")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String station;

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the vendorPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorPassword() {
        return vendorPassword;
    }

    /**
     * Sets the value of the vendorPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorPassword(String value) {
        this.vendorPassword = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the practiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPracticeName() {
        return practiceName;
    }

    /**
     * Sets the value of the practiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPracticeName(String value) {
        this.practiceName = value;
    }

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStation(String value) {
        this.station = value;
    }

}
