//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommandType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommandType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="send_patient"/>
 *     &lt;enumeration value="update_medication"/>
 *     &lt;enumeration value="update_patient"/>
 *     &lt;enumeration value="update_prescription"/>
 *     &lt;enumeration value="get_notification_count"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CommandType")
@XmlEnum
public enum CommandType {


    /**
     * 
     * 						Upload new or changed <Patient> records to Rcopia.
     * 					
     * 
     */
    @XmlEnumValue("send_patient")
    SEND_PATIENT("send_patient"),

    /**
     * 
     * 						Downloads new and changed medication records, including <Sig> details.
     *                     
     * 
     */
    @XmlEnumValue("update_medication")
    UPDATE_MEDICATION("update_medication"),

    /**
     * 
     * 						Downloads new and changed <Patient> records.
     * 					
     * 
     */
    @XmlEnumValue("update_patient")
    UPDATE_PATIENT("update_patient"),

    /**
     * 
     * 						Downloads <Prescription> records since a given date. Can be filtered by patient and status.
     * 					
     * 
     */
    @XmlEnumValue("update_prescription")
    UPDATE_PRESCRIPTION("update_prescription"),

    /**
     * 
     *                         Returns counts of any pending items that require action. May be limited by provider and/or patient.
     *                     
     * 
     */
    @XmlEnumValue("get_notification_count")
    GET_NOTIFICATION_COUNT("get_notification_count");
    private final String value;

    CommandType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommandType fromValue(String v) {
        for (CommandType c: CommandType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
