//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DrugType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrugType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="NDCID" type="{http://www.drfirst.com/}NDCIDType" minOccurs="0"/>
 *         &lt;element name="FirstDataBankMedID" type="{http://www.drfirst.com/}AN20" minOccurs="0"/>
 *         &lt;element name="RcopiaID" type="{http://www.drfirst.com/}RcopiaIDType" minOccurs="0"/>
 *         &lt;element name="BrandName" type="{http://www.drfirst.com/}AN100" minOccurs="0"/>
 *         &lt;element name="GenericName" type="{http://www.drfirst.com/}AN100" minOccurs="0"/>
 *         &lt;element name="BrandType" type="{http://www.drfirst.com/}BrandTypeType" minOccurs="0"/>
 *         &lt;element name="Route" type="{http://www.drfirst.com/}AN30" minOccurs="0"/>
 *         &lt;element name="GenericID" type="{http://www.drfirst.com/}NDCIDType" minOccurs="0"/>
 *         &lt;element name="Form" type="{http://www.drfirst.com/}AN40" minOccurs="0"/>
 *         &lt;element name="Strength" type="{http://www.drfirst.com/}AN100" minOccurs="0"/>
 *         &lt;element name="Schedule" type="{http://www.drfirst.com/}N1" minOccurs="0"/>
 *         &lt;element name="RouteCode" type="{http://www.drfirst.com/}A2" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrugType", propOrder = {

})
public class DrugType {

    @XmlElement(name = "NDCID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ndcid;
    @XmlElement(name = "FirstDataBankMedID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String firstDataBankMedID;
    @XmlElement(name = "RcopiaID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rcopiaID;
    @XmlElement(name = "BrandName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String brandName;
    @XmlElement(name = "GenericName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String genericName;
    @XmlElement(name = "BrandType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String brandType;
    @XmlElement(name = "Route")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String route;
    @XmlElement(name = "GenericID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String genericID;
    @XmlElement(name = "Form")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String form;
    @XmlElement(name = "Strength")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String strength;
    @XmlElement(name = "Schedule")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String schedule;
    @XmlElement(name = "RouteCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String routeCode;

    /**
     * Gets the value of the ndcid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNDCID() {
        return ndcid;
    }

    /**
     * Sets the value of the ndcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNDCID(String value) {
        this.ndcid = value;
    }

    /**
     * Gets the value of the firstDataBankMedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstDataBankMedID() {
        return firstDataBankMedID;
    }

    /**
     * Sets the value of the firstDataBankMedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstDataBankMedID(String value) {
        this.firstDataBankMedID = value;
    }

    /**
     * Gets the value of the rcopiaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcopiaID() {
        return rcopiaID;
    }

    /**
     * Sets the value of the rcopiaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcopiaID(String value) {
        this.rcopiaID = value;
    }

    /**
     * Gets the value of the brandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * Sets the value of the brandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandName(String value) {
        this.brandName = value;
    }

    /**
     * Gets the value of the genericName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericName() {
        return genericName;
    }

    /**
     * Sets the value of the genericName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericName(String value) {
        this.genericName = value;
    }

    /**
     * Gets the value of the brandType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandType() {
        return brandType;
    }

    /**
     * Sets the value of the brandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandType(String value) {
        this.brandType = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the genericID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericID() {
        return genericID;
    }

    /**
     * Sets the value of the genericID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericID(String value) {
        this.genericID = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForm(String value) {
        this.form = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrength(String value) {
        this.strength = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedule(String value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the routeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteCode() {
        return routeCode;
    }

    /**
     * Sets the value of the routeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteCode(String value) {
        this.routeCode = value;
    }

}
