//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the flinn.flinn.rcopia.model package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RcExtResponse_QNAME = new QName("http://www.drfirst.com/", "RcExtResponse");
    private final static QName _RCExtRequest_QNAME = new QName("http://www.drfirst.com/", "RCExtRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: flinn.flinn.rcopia.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CallerType }
     * 
     */
    public CallerType createCallerType() {
        return new CallerType();
    }

    /**
     * Create an instance of {@link PharmacyType }
     * 
     */
    public PharmacyType createPharmacyType() {
        return new PharmacyType();
    }

    /**
     * Create an instance of {@link DrugIDType }
     * 
     */
    public DrugIDType createDrugIDType() {
        return new DrugIDType();
    }

    /**
     * Create an instance of {@link ProblemListType }
     * 
     */
    public ProblemListType createProblemListType() {
        return new ProblemListType();
    }

    /**
     * Create an instance of {@link ComplexRcopiaIDType }
     * 
     */
    public ComplexRcopiaIDType createComplexRcopiaIDType() {
        return new ComplexRcopiaIDType();
    }

    /**
     * Create an instance of {@link TraceInformationType }
     * 
     */
    public TraceInformationType createTraceInformationType() {
        return new TraceInformationType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link RcopiaOrExternalID }
     * 
     */
    public RcopiaOrExternalID createRcopiaOrExternalID() {
        return new RcopiaOrExternalID();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link PatientListTypeReq }
     * 
     */
    public PatientListTypeReq createPatientListTypeReq() {
        return new PatientListTypeReq();
    }

    /**
     * Create an instance of {@link WarningListType }
     * 
     */
    public WarningListType createWarningListType() {
        return new WarningListType();
    }

    /**
     * Create an instance of {@link NotificationCountType }
     * 
     */
    public NotificationCountType createNotificationCountType() {
        return new NotificationCountType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link PatientTypeReq }
     * 
     */
    public PatientTypeReq createPatientTypeReq() {
        return new PatientTypeReq();
    }

    /**
     * Create an instance of {@link MedicationListType }
     * 
     */
    public MedicationListType createMedicationListType() {
        return new MedicationListType();
    }

    /**
     * Create an instance of {@link PrescriptionReferenceType }
     * 
     */
    public PrescriptionReferenceType createPrescriptionReferenceType() {
        return new PrescriptionReferenceType();
    }

    /**
     * Create an instance of {@link NotificationCountListType }
     * 
     */
    public NotificationCountListType createNotificationCountListType() {
        return new NotificationCountListType();
    }

    /**
     * Create an instance of {@link MedicationType }
     * 
     */
    public MedicationType createMedicationType() {
        return new MedicationType();
    }

    /**
     * Create an instance of {@link DrugType }
     * 
     */
    public DrugType createDrugType() {
        return new DrugType();
    }

    /**
     * Create an instance of {@link MedicationType.Prescription }
     * 
     */
    public MedicationType.Prescription createMedicationTypePrescription() {
        return new MedicationType.Prescription();
    }

    /**
     * Create an instance of {@link SigDataType }
     * 
     */
    public SigDataType createSigDataType() {
        return new SigDataType();
    }

    /**
     * Create an instance of {@link SimplePatientType }
     * 
     */
    public SimplePatientType createSimplePatientType() {
        return new SimplePatientType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link RcExtResponseType }
     * 
     */
    public RcExtResponseType createRcExtResponseType() {
        return new RcExtResponseType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link ProblemType }
     * 
     */
    public ProblemType createProblemType() {
        return new ProblemType();
    }

    /**
     * Create an instance of {@link RcExtRequestType }
     * 
     */
    public RcExtRequestType createRcExtRequestType() {
        return new RcExtRequestType();
    }

    /**
     * Create an instance of {@link PatientListType }
     * 
     */
    public PatientListType createPatientListType() {
        return new PatientListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RcExtResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drfirst.com/", name = "RcExtResponse")
    public JAXBElement<RcExtResponseType> createRcExtResponse(RcExtResponseType value) {
        return new JAXBElement<RcExtResponseType>(_RcExtResponse_QNAME, RcExtResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RcExtRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drfirst.com/", name = "RCExtRequest")
    public JAXBElement<RcExtRequestType> createRCExtRequest(RcExtRequestType value) {
        return new JAXBElement<RcExtRequestType>(_RCExtRequest_QNAME, RcExtRequestType.class, null, value);
    }

}
