//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PatientTypeReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientTypeReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="RcopiaID" type="{http://www.drfirst.com/}RcopiaIDType" minOccurs="0"/>
 *             &lt;element name="ExternalID" type="{http://www.drfirst.com/}ExternalIDType" minOccurs="0"/>
 *             &lt;sequence minOccurs="0">
 *               &lt;element name="Deleted" type="{http://www.drfirst.com/}YNType" minOccurs="0"/>
 *               &lt;element name="AliasForPatient" type="{http://www.drfirst.com/}RcopiaOrExternalID" minOccurs="0"/>
 *               &lt;element name="Prefix" type="{http://www.drfirst.com/}AN10" minOccurs="0"/>
 *               &lt;element name="FirstName" type="{http://www.drfirst.com/}AN35"/>
 *               &lt;element name="MiddleName" type="{http://www.drfirst.com/}AN35" minOccurs="0"/>
 *               &lt;element name="LastName" type="{http://www.drfirst.com/}AN35"/>
 *               &lt;element name="Suffix" type="{http://www.drfirst.com/}AN10" minOccurs="0"/>
 *               &lt;element name="DOB" type="{http://www.drfirst.com/}MDYDateType"/>
 *               &lt;element name="Sex" minOccurs="0">
 *                 &lt;simpleType>
 *                   &lt;restriction base="{http://www.drfirst.com/}A1">
 *                     &lt;enumeration value="M"/>
 *                     &lt;enumeration value="F"/>
 *                     &lt;enumeration value="U"/>
 *                   &lt;/restriction>
 *                 &lt;/simpleType>
 *               &lt;/element>
 *               &lt;element name="HomePhone" type="{http://www.drfirst.com/}AN25" minOccurs="0"/>
 *               &lt;element name="WorkPhone" type="{http://www.drfirst.com/}AN25" minOccurs="0"/>
 *               &lt;element name="OtherPhone" type="{http://www.drfirst.com/}AN25" minOccurs="0"/>
 *               &lt;element name="Address1" type="{http://www.drfirst.com/}AN50" minOccurs="0"/>
 *               &lt;element name="Address2" type="{http://www.drfirst.com/}AN50" minOccurs="0"/>
 *               &lt;element name="City" type="{http://www.drfirst.com/}AN50" minOccurs="0"/>
 *               &lt;element name="State" type="{http://www.drfirst.com/}StateCodeType" minOccurs="0"/>
 *               &lt;element name="Zip" type="{http://www.drfirst.com/}ZipCodeType" minOccurs="0"/>
 *               &lt;element name="SSN" minOccurs="0">
 *                 &lt;simpleType>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                     &lt;pattern value="\d{3}-\d{2}-\d{4}"/>
 *                   &lt;/restriction>
 *                 &lt;/simpleType>
 *               &lt;/element>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientTypeReq", propOrder = {
    "rcopiaID",
    "externalID",
    "deleted",
    "aliasForPatient",
    "prefix",
    "firstName",
    "middleName",
    "lastName",
    "suffix",
    "dob",
    "sex",
    "homePhone",
    "workPhone",
    "otherPhone",
    "address1",
    "address2",
    "city",
    "state",
    "zip",
    "ssn"
})
public class PatientTypeReq {

    @XmlElement(name = "RcopiaID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rcopiaID;
    @XmlElement(name = "ExternalID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String externalID;
    @XmlElement(name = "Deleted")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deleted;
    @XmlElement(name = "AliasForPatient")
    protected RcopiaOrExternalID aliasForPatient;
    @XmlElement(name = "Prefix")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String prefix;
    @XmlElement(name = "FirstName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String firstName;
    @XmlElement(name = "MiddleName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String middleName;
    @XmlElement(name = "LastName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastName;
    @XmlElement(name = "Suffix")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String suffix;
    @XmlElement(name = "DOB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dob;
    @XmlElement(name = "Sex")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sex;
    @XmlElement(name = "HomePhone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String homePhone;
    @XmlElement(name = "WorkPhone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String workPhone;
    @XmlElement(name = "OtherPhone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String otherPhone;
    @XmlElement(name = "Address1")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String address1;
    @XmlElement(name = "Address2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String address2;
    @XmlElement(name = "City")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String city;
    @XmlElement(name = "State")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String state;
    @XmlElement(name = "Zip")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String zip;
    @XmlElement(name = "SSN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ssn;

    /**
     * Gets the value of the rcopiaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcopiaID() {
        return rcopiaID;
    }

    /**
     * Sets the value of the rcopiaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcopiaID(String value) {
        this.rcopiaID = value;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalID() {
        return externalID;
    }

    /**
     * Sets the value of the externalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalID(String value) {
        this.externalID = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleted(String value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the aliasForPatient property.
     * 
     * @return
     *     possible object is
     *     {@link RcopiaOrExternalID }
     *     
     */
    public RcopiaOrExternalID getAliasForPatient() {
        return aliasForPatient;
    }

    /**
     * Sets the value of the aliasForPatient property.
     * 
     * @param value
     *     allowed object is
     *     {@link RcopiaOrExternalID }
     *     
     */
    public void setAliasForPatient(RcopiaOrExternalID value) {
        this.aliasForPatient = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOB(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the homePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * Sets the value of the homePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePhone(String value) {
        this.homePhone = value;
    }

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhone(String value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the otherPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherPhone() {
        return otherPhone;
    }

    /**
     * Sets the value of the otherPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherPhone(String value) {
        this.otherPhone = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

}
