//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="ServerIPAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Status">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.drfirst.com/}AN20">
 *                 &lt;enumeration value="ok"/>
 *                 &lt;enumeration value="error"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="Warnings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Error" type="{http://www.drfirst.com/}ErrorType" minOccurs="0"/>
 *           &lt;element name="AccessTime" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;pattern value="(0|[1-9]\d*)ms"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="LastUpdateDate" type="{http://www.drfirst.com/}RcopiaDateType" minOccurs="0"/>
 *           &lt;element name="MedicationList" type="{http://www.drfirst.com/}MedicationListType" minOccurs="0"/>
 *           &lt;element name="PatientList" type="{http://www.drfirst.com/}PatientListType"/>
 *         &lt;/sequence>
 *         &lt;choice>
 *           &lt;group ref="{http://www.drfirst.com/}GetNotificationCountResponse"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseType", propOrder = {
    "serverIPAddress",
    "status",
    "warnings",
    "error",
    "accessTime",
    "lastUpdateDate",
    "medicationList",
    "patientList",
    "notificationCountList"
})
public class ResponseType {

    @XmlElement(name = "ServerIPAddress")
    protected String serverIPAddress;
    @XmlElement(name = "Status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlElement(name = "Warnings", required = true)
    protected String warnings;
    @XmlElement(name = "Error")
    protected ErrorType error;
    @XmlElement(name = "AccessTime")
    protected String accessTime;
    @XmlElement(name = "LastUpdateDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastUpdateDate;
    @XmlElement(name = "MedicationList")
    protected MedicationListType medicationList;
    @XmlElement(name = "PatientList")
    protected PatientListType patientList;
    @XmlElement(name = "NotificationCountList")
    protected NotificationCountListType notificationCountList;

    /**
     * Gets the value of the serverIPAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerIPAddress() {
        return serverIPAddress;
    }

    /**
     * Sets the value of the serverIPAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerIPAddress(String value) {
        this.serverIPAddress = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarnings(String value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

    /**
     * Gets the value of the accessTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessTime() {
        return accessTime;
    }

    /**
     * Sets the value of the accessTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessTime(String value) {
        this.accessTime = value;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateDate(String value) {
        this.lastUpdateDate = value;
    }

    /**
     * Gets the value of the medicationList property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationListType }
     *     
     */
    public MedicationListType getMedicationList() {
        return medicationList;
    }

    /**
     * Sets the value of the medicationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationListType }
     *     
     */
    public void setMedicationList(MedicationListType value) {
        this.medicationList = value;
    }

    /**
     * Gets the value of the patientList property.
     * 
     * @return
     *     possible object is
     *     {@link PatientListType }
     *     
     */
    public PatientListType getPatientList() {
        return patientList;
    }

    /**
     * Sets the value of the patientList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientListType }
     *     
     */
    public void setPatientList(PatientListType value) {
        this.patientList = value;
    }

    /**
     * Gets the value of the notificationCountList property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationCountListType }
     *     
     */
    public NotificationCountListType getNotificationCountList() {
        return notificationCountList;
    }

    /**
     * Sets the value of the notificationCountList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationCountListType }
     *     
     */
    public void setNotificationCountList(NotificationCountListType value) {
        this.notificationCountList = value;
    }

}
