//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 03:02:40 PM EDT 
//


package flinn.rcopia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TraceInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TraceInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestMessageID" type="{http://www.drfirst.com/}AN40"/>
 *         &lt;element name="ResponseMessageID" type="{http://www.drfirst.com/}AN100" minOccurs="0"/>
 *         &lt;element name="DestinationURL" type="{http://www.drfirst.com/}AN100" minOccurs="0"/>
 *         &lt;element name="RequestTimestamp" type="{http://www.drfirst.com/}RcopiaDateType" minOccurs="0"/>
 *         &lt;element name="ResponseStartTimestamp" type="{http://www.drfirst.com/}RcopiaDateType" minOccurs="0"/>
 *         &lt;element name="RcopiaServerName" type="{http://www.drfirst.com/}AN40" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TraceInformationType", propOrder = {
    "requestMessageID",
    "responseMessageID",
    "destinationURL",
    "requestTimestamp",
    "responseStartTimestamp",
    "rcopiaServerName"
})
public class TraceInformationType {

    @XmlElement(name = "RequestMessageID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String requestMessageID;
    @XmlElement(name = "ResponseMessageID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String responseMessageID;
    @XmlElement(name = "DestinationURL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String destinationURL;
    @XmlElement(name = "RequestTimestamp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String requestTimestamp;
    @XmlElement(name = "ResponseStartTimestamp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String responseStartTimestamp;
    @XmlElement(name = "RcopiaServerName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rcopiaServerName;

    /**
     * Gets the value of the requestMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestMessageID() {
        return requestMessageID;
    }

    /**
     * Sets the value of the requestMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestMessageID(String value) {
        this.requestMessageID = value;
    }

    /**
     * Gets the value of the responseMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMessageID() {
        return responseMessageID;
    }

    /**
     * Sets the value of the responseMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMessageID(String value) {
        this.responseMessageID = value;
    }

    /**
     * Gets the value of the destinationURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationURL() {
        return destinationURL;
    }

    /**
     * Sets the value of the destinationURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationURL(String value) {
        this.destinationURL = value;
    }

    /**
     * Gets the value of the requestTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestTimestamp() {
        return requestTimestamp;
    }

    /**
     * Sets the value of the requestTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestTimestamp(String value) {
        this.requestTimestamp = value;
    }

    /**
     * Gets the value of the responseStartTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseStartTimestamp() {
        return responseStartTimestamp;
    }

    /**
     * Sets the value of the responseStartTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseStartTimestamp(String value) {
        this.responseStartTimestamp = value;
    }

    /**
     * Gets the value of the rcopiaServerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcopiaServerName() {
        return rcopiaServerName;
    }

    /**
     * Sets the value of the rcopiaServerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcopiaServerName(String value) {
        this.rcopiaServerName = value;
    }

}
